org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
# Один APK на все ABI. Нативного кода у нас нет вообще (голый WebView),
# поэтому сплиты по архитектурам не нужны — «универсальный» APK ставится
# и на arm64, и на armeabi-v7a, и на x86_64-эмулятор.
android.enableJetifier=false
